#!/bin/bash
#### Author: Snow Dimon ####
#### Website: snowdimon.ru ####

f=`yandex-disk publish "$*" | xclip -filter -selection clipboard`
zenity --info --window-icon /usr/share/yd-tools/icons/yd-128_g.png --title="Yandex.Disk" --ok-label="Закрыть" --text="Ссылка на файл $*

$f

скопирована в буфер обмена."
